"""add real film forecasting platform

Revision ID: 6f711c5e7523
Revises: 20260724_0001
Create Date: 2026-07-24 20:51:38.047497
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6f711c5e7523"
down_revision: str | None = "20260724_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("origin_country", sa.String(length=8), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_id", name="uq_companies_source_id"),
    )
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_table(
        "job_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_name", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cursor_json", sa.Text(), nullable=False),
        sa.Column("stats_json", sa.Text(), nullable=False),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_job_runs_name_started", "job_runs", ["job_name", "started_at"], unique=False
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("model_kind", sa.String(length=48), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=True),
        sa.Column("artifact_checksum", sa.String(length=64), nullable=True),
        sa.Column("feature_manifest_json", sa.Text(), nullable=False),
        sa.Column("metrics_json", sa.Text(), nullable=False),
        sa.Column("training_cutoff", sa.Date(), nullable=True),
        sa.Column("promoted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_versions_version"), "model_versions", ["version"], unique=True)
    op.create_table(
        "movies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("original_title", sa.String(length=300), nullable=True),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.Column("release_status", sa.String(length=32), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=False),
        sa.Column("date_precision", sa.String(length=16), nullable=False),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("certification", sa.String(length=24), nullable=True),
        sa.Column("original_language", sa.String(length=16), nullable=True),
        sa.Column("origin_country", sa.String(length=8), nullable=True),
        sa.Column("genres_json", sa.Text(), nullable=False),
        sa.Column("budget", sa.Float(), nullable=True),
        sa.Column("budget_status", sa.String(length=24), nullable=False),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("backdrop_url", sa.Text(), nullable=True),
        sa.Column("trailer_url", sa.Text(), nullable=True),
        sa.Column("homepage_url", sa.Text(), nullable=True),
        sa.Column("primary_source", sa.String(length=32), nullable=False),
        sa.Column("source_confidence", sa.Float(), nullable=False),
        sa.Column("data_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movies_release_date"), "movies", ["release_date"], unique=False)
    op.create_index(op.f("ix_movies_release_status"), "movies", ["release_status"], unique=False)
    op.create_index(
        "ix_movies_release_status_date", "movies", ["release_status", "release_date"], unique=False
    )
    op.create_index(op.f("ix_movies_release_year"), "movies", ["release_year"], unique=False)
    op.create_index(
        "ix_movies_release_year_title", "movies", ["release_year", "title"], unique=False
    )
    op.create_index(op.f("ix_movies_slug"), "movies", ["slug"], unique=True)
    op.create_index(op.f("ix_movies_title"), "movies", ["title"], unique=False)
    op.create_table(
        "people",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("profile_url", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_id", name="uq_people_source_id"),
    )
    op.create_index("ix_people_name", "people", ["name"], unique=False)
    op.create_table(
        "actual_grosses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("movie_id", sa.String(length=36), nullable=False),
        sa.Column("target", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("amount_status", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_checksum", sa.String(length=64), nullable=False),
        sa.Column("conflict_group", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "movie_id", "target", "source", "observed_at", name="uq_actual_observation"
        ),
    )
    op.create_index(
        "ix_actual_movie_target_time",
        "actual_grosses",
        ["movie_id", "target", "observed_at"],
        unique=False,
    )
    op.create_table(
        "buzz_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("movie_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("normalized_value", sa.Float(), nullable=True),
        sa.Column("momentum", sa.Float(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("raw_checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("movie_id", "source", "metric", "observed_at", name="uq_buzz_snapshot"),
    )
    op.create_index(
        "ix_buzz_movie_time", "buzz_snapshots", ["movie_id", "observed_at"], unique=False
    )
    op.create_table(
        "credits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("movie_id", sa.String(length=36), nullable=False),
        sa.Column("person_id", sa.String(length=36), nullable=False),
        sa.Column("department", sa.String(length=48), nullable=False),
        sa.Column("job", sa.String(length=96), nullable=False),
        sa.Column("character_name", sa.String(length=300), nullable=False),
        sa.Column("billing_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "movie_id",
            "person_id",
            "department",
            "job",
            "character_name",
            name="uq_credit_identity",
        ),
    )
    op.create_index(
        "ix_credits_movie_department_order",
        "credits",
        ["movie_id", "department", "billing_order"],
        unique=False,
    )
    op.create_table(
        "external_identifiers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("movie_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("movie_id", "source", name="uq_external_identifier_movie_source"),
        sa.UniqueConstraint("source", "external_id", name="uq_external_identifier_source_value"),
    )
    op.create_index(
        op.f("ix_external_identifiers_external_id"),
        "external_identifiers",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_identifiers_source"), "external_identifiers", ["source"], unique=False
    )
    op.create_table(
        "forecast_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("movie_id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("data_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=True),
        sa.Column("forecast_type", sa.String(length=32), nullable=False),
        sa.Column("targets_json", sa.Text(), nullable=False),
        sa.Column("factors_json", sa.Text(), nullable=False),
        sa.Column("buzz_json", sa.Text(), nullable=False),
        sa.Column("comparables_json", sa.Text(), nullable=False),
        sa.Column("fairness_json", sa.Text(), nullable=False),
        sa.Column("evidence_manifest_json", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("feature_manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("limitations_json", sa.Text(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "movie_id",
            "model_version_id",
            "data_cutoff",
            "horizon_days",
            "forecast_type",
            name="uq_forecast_lock",
        ),
    )
    op.create_index(
        "ix_forecast_movie_cutoff", "forecast_runs", ["movie_id", "data_cutoff"], unique=False
    )
    op.create_index(
        op.f("ix_forecast_runs_data_cutoff"), "forecast_runs", ["data_cutoff"], unique=False
    )
    op.create_table(
        "movie_companies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("movie_id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=48), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("movie_id", "company_id", "role", name="uq_movie_company_role"),
    )
    op.create_table(
        "source_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("movie_id", sa.String(length=36), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("observation_type", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("raw_checksum", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("forecast_eligible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "movie_id", "source", "observation_type", "raw_checksum", name="uq_observation_checksum"
        ),
    )
    op.create_index(
        "ix_observations_movie_time",
        "source_observations",
        ["movie_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_observations_movie_id"), "source_observations", ["movie_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_observations_observation_type"),
        "source_observations",
        ["observation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_observations_observed_at"),
        "source_observations",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_observations_source"), "source_observations", ["source"], unique=False
    )
    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("movie_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "movie_id", name="uq_watchlist_user_movie"),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("forecast_run_id", sa.String(length=36), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("ledger_hash", sa.String(length=64), nullable=False),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["forecast_run_id"], ["forecast_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("forecast_run_id"),
    )
    op.create_index(
        op.f("ix_ledger_entries_ledger_hash"), "ledger_entries", ["ledger_hash"], unique=True
    )
    op.create_index(op.f("ix_ledger_entries_sequence"), "ledger_entries", ["sequence"], unique=True)
    op.create_table(
        "releases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("movie_id", sa.String(length=36), nullable=False),
        sa.Column("country_code", sa.String(length=8), nullable=False),
        sa.Column("release_type", sa.String(length=32), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=False),
        sa.Column("certification", sa.String(length=24), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_confirmed", sa.Boolean(), nullable=False),
        sa.Column("source_observation_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_observation_id"], ["source_observations.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "movie_id", "country_code", "release_type", "release_date", name="uq_release_identity"
        ),
    )
    op.create_index(
        "ix_releases_country_date", "releases", ["country_code", "release_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_releases_country_date", table_name="releases")
    op.drop_table("releases")
    op.drop_index(op.f("ix_ledger_entries_sequence"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_ledger_hash"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_table("watchlist_items")
    op.drop_index(op.f("ix_source_observations_source"), table_name="source_observations")
    op.drop_index(op.f("ix_source_observations_observed_at"), table_name="source_observations")
    op.drop_index(op.f("ix_source_observations_observation_type"), table_name="source_observations")
    op.drop_index(op.f("ix_source_observations_movie_id"), table_name="source_observations")
    op.drop_index("ix_observations_movie_time", table_name="source_observations")
    op.drop_table("source_observations")
    op.drop_table("movie_companies")
    op.drop_index(op.f("ix_forecast_runs_data_cutoff"), table_name="forecast_runs")
    op.drop_index("ix_forecast_movie_cutoff", table_name="forecast_runs")
    op.drop_table("forecast_runs")
    op.drop_index(op.f("ix_external_identifiers_source"), table_name="external_identifiers")
    op.drop_index(op.f("ix_external_identifiers_external_id"), table_name="external_identifiers")
    op.drop_table("external_identifiers")
    op.drop_index("ix_credits_movie_department_order", table_name="credits")
    op.drop_table("credits")
    op.drop_index("ix_buzz_movie_time", table_name="buzz_snapshots")
    op.drop_table("buzz_snapshots")
    op.drop_index("ix_actual_movie_target_time", table_name="actual_grosses")
    op.drop_table("actual_grosses")
    op.drop_index("ix_people_name", table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_movies_title"), table_name="movies")
    op.drop_index(op.f("ix_movies_slug"), table_name="movies")
    op.drop_index("ix_movies_release_year_title", table_name="movies")
    op.drop_index(op.f("ix_movies_release_year"), table_name="movies")
    op.drop_index("ix_movies_release_status_date", table_name="movies")
    op.drop_index(op.f("ix_movies_release_status"), table_name="movies")
    op.drop_index(op.f("ix_movies_release_date"), table_name="movies")
    op.drop_table("movies")
    op.drop_index(op.f("ix_model_versions_version"), table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_index("ix_job_runs_name_started", table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
